In [4]:
import torch
import pandas as pd

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [11]:
class Dataset():

    def __init__(self, path):
        self.raw_data = pd.read_csv(path)

In [12]:
train, test = Dataset("data/series/train/merged_data.csv"), Dataset("data/series/test/merged_data.csv")

In [13]:
train.raw_data

,x,g,sea_zero_lv,bath,ts,t_base,t_moho,m_lv,File
0,0.000000,-74.439863,0.0,0.000000,0.000000,9208.154533,32063.683064,40000.0,dado_1
1,502.512563,-72.092957,0.0,0.000000,0.000000,9203.470951,32156.465640,40000.0,dado_1
2,1005.025126,-71.399166,0.0,0.000000,0.000000,9198.787369,32249.248217,40000.0,dado_1
3,1507.537688,-72.527916,0.0,0.000000,0.000000,9194.103786,32342.030793,40000.0,dado_1
4,2010.050251,-74.196375,0.0,0.000000,0.000000,9189.420204,32434.813369,40000.0,dado_1
...,...,...,...,...,...,...,...,...,...
1595,97989.949749,26.170785,0.0,5806.265155,6508.955241,13847.156105,20058.812439,40000.0,dado_8
1596,98492.462312,40.221606,0.0,5805.083762,6477.077354,13972.725987,20058.432697,40000.0,dado_8
1597,98994.974874,47.846142,0.0,5803.896006,6439.760511,14092.856913,20058.052955,40000.0,dado_8
1598,99497.487437,33.072072,0.0,5802.701888,6397.013258,14207.557430,20057.673214,40000.0,dado_8
1599,100000.000000,-2.016833,0.0,5801.501413,6348.876920,14316.868861,20057.293472,40000.0,dado_8